### ISSUE TITLE
Console window keeps getting bigger

### ISSUE THREAD

**Issue by kafeijao** [yamiM0NSTER/ML.ConstantConsolePos#1]
Hello! First of all thanks for this awesome plugin!

I'm having an issue where my console keeps growing every time I open, eventually going out of border. I'm dragging the console to my second monitor on the left, other than that it might be that the monitors are on different resolutions ;_;

**Comment by yamiM0NSTER** [comment]
Hello!

First of all I am glad you enjoy the plugin idea. 

Let me start with apology as the current project name and description doesn't really describe what it does properly. In fact both console size and position are persistent between game launches. Similar to you I have multiple displays: 1920x1080 and 2560x1440. The way it works for me currently is game and console start on bigger monitor and then plugin moves and resizes console **after** game window opens to smaller one. Unfortunately there is no way for me to make it happen faster as melon loader doesn't provide such early callback (maybe `OnPreferencesLoaded` but I didn't test that). After game opens any size or position change should be saved, and once more at proper game exit.

I am not sure if you are simply inpatient or expect a window to look same on different displays but that's really not a result you should expect, I guess? Maybe I am misunderstanding your issue but feel free to elaborate if I am wrong. That said project name will probably be updated to better reflect functionality.

**Comment by kafeijao** [comment]
Ok so, my issue is:

1. I start fresh without (after resetting melon config settings).
2. The console is on it's default position.
3. When I drag the console to my other monitor (it looks different size because different resolutions (and that's fine))
4. I then close the game
5. When I open the game again, the console moves, to the right place, but it became bigger than it was.
6. I then close the game
7. Open -> Bigger
8. Rinse and repeat from 6.

And if I keep doing this, eventually will go out of bounds (the top and left distance is fine, seems like the distance to the right and to the bottom keeps increasing after restarts).

What I noticed is that the console size is not constant, I was printing out the `rect` coords and also the `rect` width and height (using the struct functions). On my higher res monitor the `width` and `height` actually increase comparing with my first monitor.

So what I think it's happening is when calling the SetPosition it uses the `width` and `height` that calculates using the first monitor, and then when moves it increases that size, and saves the increased size. So I "fixed it" by making the size static.

Maybe I have some weird windows setting changing the size of my windows, idk ;_;
My resolutions:
1920x1080
2560x1440

**Comment by kafeijao** [comment]
Found the culprit!

![image](https://user-images.githubusercontent.com/4409693/187070297-47e620de-e52b-4dc6-b616-6994f0e20eed.png)

My higher rez monitor has 125% while on my lower one was at 100%, I guess this does affect the window size. When I make both screens 100% the problem doesn't happen anymore.

Didn't even think of checking this, just assume it was because I had different resolutions.

I guess this is particular to my setup so feel free to close the issue, sorry for taking your time and thanks!

**Comment by yamiM0NSTER** [comment]
Hmm that's actually interesting. Normally I'd assume windows scaling shouldn't be an issue. I'll have to look into that and how to handle it properly, as there may be more people using that.

**Comment by yamiM0NSTER** [comment]
So uhh it seems changing `SetWindowPos` call to 2 separate calls for position and size fixes the odd behaviour. I also removed not needed flags so those could have caused that. Feel free to pull latest source or download pre release from [here](https://github.com/yamiM0NSTER/ML.PersistentConsole/releases/tag/v1.0.1) and let me know if issue is gone for you too.

PS: Make sure to remove dll with old name.

**Comment by yamiM0NSTER** [comment]
Closing due to no response in almost a month.

If you feel this issue was not resolved in `v1.0.1` version, you can reopen.
